version: "3.8"
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    command:
      - -storageDataPath=/vm-data
      - -retentionPeriod=7d   # уменьшите хранение ради экономии диска
      - -promscrape.config=/etc/scrape.yml
      - -vmui.customDashboardsPath=/dashboards
    ports:
      - "8428:8428" 
    network_mode: host
    volumes:
      - ./vm-data:/vm-data
      - ./scrape.yml:/etc/scrape.yml:ro
      - ./dashboards:/dashboards:ro

  json-exporter:
    build: ./exporter/
    container_name: json-exporter
    restart: unless-stopped
    ports:
      - "7979:7979"
    environment:
      SOURCE: "http://127.0.0.1:11111/debug/vars" 
      LISTEN: "0.0.0.0:7979"
      TIMEOUT: "5"
      DELAY_UNIT: "ms"   # поменяй на "s", если delay уже в секундах
      LOG_LEVEL: "DEBUG"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:7979/metrics"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    network_mode: host    
    
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    
    network_mode: host
    environment:
      GF_SERVER_HTTP_ADDR: 127.0.0.1
    user: "472:472"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-dashboards:/var/lib/grafana/dashboards
      - ./grafana-provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./grafana-provisioning/alert-rules:/etc/grafana/provisioning/alerting/rules



  victorialogs:
    image: victoriametrics/victoria-logs:latest
    command:
      - -storageDataPath=/vl-data
      - -retentionPeriod=7d    # по умолчанию у VL как раз 7 дней
    ports:
      - "9428:9428"            # UI: http://localhost:9428/select/vmui
      - "1514:1514/udp"        # (опц.) syslog UDP
      - "1514:1514"            # (опц.) syslog TCP
    volumes:
      - ./vl-data:/vl-data

