version: "3.8"
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    command:
      - -storageDataPath=/vm-data
      - -retentionPeriod=7d   # уменьшите хранение ради экономии диска
    ports:
      - "8428:8428" 
    network_mode: host
    volumes:
      - vm-data:/vm-data

  json-exporter:
    build: ./exporter/
    container_name: json-exporter
    restart: unless-stopped
    ports:
      - "9108:9108"
    environment:
      SOURCE: "http://127.0.0.1:11111/debug/vars" 
      LISTEN: "0.0.0.0:9108"
      TIMEOUT: "5"
      DELAY_UNIT: "ms"   # поменяй на "s", если delay уже в секундах
      LOG_LEVEL: "DEBUG"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:9108/metrics"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    network_mode: host    

  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: vmagent
    restart: unless-stopped
    command:
      - -promscrape.config=/etc/scrape.yml
      - -remoteWrite.url=http://127.0.0.1:8428/api/v1/write
    network_mode: host
    volumes:
      - ./scrape.yml:/etc/scrape.yml:ro
    
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    
    network_mode: host
    environment:
      GF_SERVER_HTTP_ADDR: 127.0.0.1
    user: "472:472"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-dashboards:/var/lib/grafana/dashboards
      - ./grafana-provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./grafana-provisioning/alert-rules:/etc/grafana/provisioning/alerting/rules

volumes:
  vm-data:
  grafana-data:

