global:
  scrape_interval: 15s

scrape_configs:
  - job_name: xray-core-metrics
    static_configs:
      - targets: ['json-exporter-core:9108']

  - job_name: xray-ui-metrics
    static_configs:
      - targets: ['json-exporter-ui:9108']

  - job_name: xray-checker
    scrape_interval: 20s
    static_configs:
      - targets: ['xray-checker:2112']

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up|process_start_time_seconds'
        action: keep

