global:
  scrape_interval: 15s

scrape_configs:
  - job_name: xray-core-metrics
    static_configs:
      - targets: ['json-exporter:9108']

  - job_name: xray-checker
    static_configs:
      - targets: ['xray-checker:2112']

